name: 填报

on:
  push:
  schedule:
    - cron: '0 22 * * *'
# 每天在国际标准时间22点（北京时间+8，即早上6点）运行


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装Python下的requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: 填报
      run: |
        python test.py ${{secrets.LOGIN_ID}} ${{secrets.LOGIN_PWD}} ${{secrets.LOGIN_PWD}} ${{secrets.HOUSEHOLD_REGISTER}} ${{secrets.PHONE_NUMBER}} ${{secrets.CURRENT_LOCATION}}
