name: 填报

on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 安装Python下的requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: 填报
      run: |
        python test.py
